export const ADD_POST = 'ADD_POST'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const DELETE_POST = 'DELETE_POST'

export const FOLLOW = 'FOLLOW'
export const UNFOLLOW = 'UNFOLLOW'
export const SET_USERS = 'SET_USERS'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT'
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING'

export const SET_USER_PROFILE = 'SET_USER_PROFILE'

export const SET_USER_DATA = 'SET_USER_DATA'

export const TOGGLE_FOLLOWING_IN_PROGRESS = 'TOGGLE_FOLLOWING_IN_PROGRESS'

export const SET_STATUS = 'SET_STATUS'

export const INITIALIZED_SUCCESS = 'INITIALIZED_SUCCESS'